###
### GET Something
GET http://localhost:8080/items/5634 HTTP/1.1


###
### PUT Something
PUT http://localhost:8080/items/5634 HTTP/1.1

{
    "name" : "Something",
    "test" : "Just to see what is returned. muhahaha"
}

###
### PUT Something with extra slash
PUT http://localhost:8080/items/5634/ HTTP/1.1

{
    "name" : "Something",
    "test" : "Just to see if ot works with extra slash"
}

###
### PUT with mismatch between id and address should give error
PUT http://localhost:8080/items/5634 HTTP/1.1

{
    "id" : "mismatch-with-address",
    "name" : "Something",
    "test" : "Just to see what is returned. muhahaha"
}

###
### DELETE Something
DELETE http://localhost:8080/items/5634 HTTP/1.1

###
### DELETE Something with extra slash
DELETE http://localhost:8080/items/5634/ HTTP/1.1


###
### POST Something - Missing Id
POST http://localhost:8080/api/items/ HTTP/1.1

{
    "name" : "Something Else",
    "test" : "Should not be added, missing id"
}


###
### POST Something - Invalid JSON
POST http://localhost:8080/api/items/ HTTP/1.1

"Just some plain text"


###
### POST Something
POST http://localhost:8080/api/items/ HTTP/1.1

{
    "id" : "new-added-with-post",
    "name" : "Something Entirely Different",
    "test" : "Should be added using the id"
}

###
### GET Something
GET http://localhost:8080/api/items/new-added-with-post HTTP/1.1


###
### POST Multiple items
POST http://localhost:8080/api/items/ HTTP/1.1

[
    {
        "id" : "item-001",
        "name" : "First of 3"
    },
    {
        "id" : "item-002",
        "name" : "Second of 2",
        "second" : "To show flexibility"
    },
    {
        "id" : "item-003",
        "name" : "Third of 3",
        "third" : "We use different schema"
    }
]

###
### GET item 1
GET http://localhost:8080/api/items/item-001 HTTP/1.1

###
### GET item 2
GET http://localhost:8080/api/items/item-002 HTTP/1.1

###
### GET item 3
GET http://localhost:8080/api/items/item-003 HTTP/1.1


###
### GET Something
GET http://localhost:8080/api/items/ HTTP/1.1


###
### PATCH Something - Not Implemented
PATCH http://localhost:8080/items/5634 HTTP/1.1


###
### POST without ending /
POST http://localhost:8080/api/items HTTP/1.1

{
    "id" : "item-001",
    "name" : "Item no Slash",
    "test" : "Posted without slash"
}

###
### GET with slash should return it
GET http://localhost:8080/api/items/item-001 HTTP/1.1


###
### GET with slash should not return it
GET http://localhost:8080/api/itemsitem-001 HTTP/1.1

###
### GET with extra slash should also return it
GET http://localhost:8080/api/items/item-001/ HTTP/1.1



###
### GET test case 001
GET http://192.168.64.20:31331/tests/testcase-001 HTTP/1.1



###
### POST test case 001
POST http://192.168.64.20:31331/tests/ HTTP/1.1

{
    "id" : "testcase-001",
    "name" : "First Test Case",
    "description" : "Just a simple test case"
}